create table countries (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    code varchar(8) not null,
    constraint uk_countries_code unique (code),
    constraint uk_countries_name unique (name)
);

create table cities (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    country_id bigint not null,
    constraint fk_cities_country foreign key (country_id) references countries (id)
);

create table customers (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    date_of_birth date not null,
    nic_number varchar(255) not null,
    constraint uk_customers_nic_number unique (nic_number)
);

create table customer_mobile_numbers (
    id bigint generated by default as identity primary key,
    mobile_number varchar(255) not null,
    customer_id bigint not null,
    constraint fk_customer_mobile_numbers_customer foreign key (customer_id) references customers (id)
);

create table customer_addresses (
    id bigint generated by default as identity primary key,
    address_line1 varchar(255) not null,
    address_line2 varchar(255),
    city_id bigint not null,
    country_id bigint not null,
    customer_id bigint not null,
    constraint fk_customer_addresses_city foreign key (city_id) references cities (id),
    constraint fk_customer_addresses_country foreign key (country_id) references countries (id),
    constraint fk_customer_addresses_customer foreign key (customer_id) references customers (id)
);

create table customer_family_members (
    customer_id bigint not null,
    family_member_id bigint not null,
    constraint pk_customer_family_members primary key (customer_id, family_member_id),
    constraint fk_customer_family_members_customer foreign key (customer_id) references customers (id),
    constraint fk_customer_family_members_family_member foreign key (family_member_id) references customers (id)
);

create table bulk_import_jobs (
    id bigint generated by default as identity primary key,
    mode varchar(32),
    status varchar(32),
    file_name varchar(255),
    total_rows bigint not null default 0,
    processed_rows bigint not null default 0,
    success_rows bigint not null default 0,
    failure_rows bigint not null default 0,
    error_message varchar(2000),
    created_at timestamp,
    updated_at timestamp
);